theme: jekyll-theme-cayman
show_downloads: true
github:
  zip_url: https://github.com/MineralsCloud/EquationsOfStateOfSolids.jl/archive/refs/tags/v0.1.1.zip
  tar_url: https://github.com/MineralsCloud/EquationsOfStateOfSolids.jl/archive/refs/tags/v0.1.1.tar.gz
